=== adamitdeka/xml_and_php/xml/tickets.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="status">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="sdate" type="xs:date"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="subject" type="xs:string"/>
                            <xs:element name="message" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="sentby" type="xs:unsignedInt" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                        <xs:attribute name="userid" type="xs:unsignedInt" use="required" />
                        <xs:attribute name="ts" type="xs:dateTime" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== adamitdeka/xml_and_php/xml/tickets.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
    <!--doi is date of issue and toi is time of issue-->
    <ticket id="1" userid="10024" ts="2019-05-02T18:45:36">
    <!--sdate is status date-->
        <status sdate="2019-05-02">ongoing</status>
        <subject>Laptop touchpad not working</subject>
        <message sentby="10024"> I have a lenevo ideapad 330s. Touchpad is not working. I tried reinstalling the drivers.</message>
        <message sentby="20056">Please try restarting your laptop after installing the drivers.</message>
    </ticket>
    <ticket id="2" userid="10025" ts="2018-02-05T21:36:15">
        <status sdate="2018-02-16">Resolved</status>
        <subject>Laptop touchpad not working</subject>
        <message sentby="10024"> I have a lenevo ideapad 330s. Touchpad is not working. I tried reinstalling the drivers.</message>
        <message sentby="20056">Please try restarting your laptop after installing the drivers.</message>
    </ticket>
<ticket id="3" userid="10024" ts="2020-03-23T21:50:23"><status sdate="2020-03-23">resolved</status><subject>speakers are making buzzing noise</subject><message sentby="10024">how to remove the noise coming from speakers</message></ticket><ticket id="4" userid="10024" ts="2020-03-24T01:31:11"><status sdate="2020-03-24">ongoing</status><subject>line in display</subject><message sentby="10024">a black line is showing in display when I restarted my laptop</message></ticket></tickets>
